name = "interagift"
main = ".open-next/worker.js"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "interagift-db"
database_id = "b6e44f1b-1a9e-4256-ab66-057f77403842"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "interagift-media"

[vars]
ADMIN_EMAIL = "rotembit53@gmail.com"
